FROM node:18
WORKDIR /usr/src/app

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copiar todo el código
COPY . .

EXPOSE 3000
CMD ["npm", "run", "start"]
